### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by joeclark340** [Natram1zh/Apex-Legends-Config-And-Tweaks#11]
i dont see any improvement and i also dont think the autoexec worked for me

**Comment by joeclark340** [comment]
it also seems worse for me

**Comment by Natram1zh** [comment]
What is your PC specs and did you checked with benchmark tools like capframex, rtss overlay or presentmon?

**Comment by progun228** [comment]
Sometimes when you fall out of the plane, the inventory and map interface will disappear, as well as the cursor. This is usually corrected immediately when you already sit down on the ground, but sometimes the game crashes. There were two crashes in 3 days.

**Comment by Natram1zh** [comment]
The inventory and map interface will disappear can be cause by -dev but other things happens because of apex, mainly that cursor. For crashes I don't know, it would be your PC, check if it has any file in crashpad (C:\Program Files (x86)\Steam\steamapps\common\Apex Legends\Crashpad\db) if it doesn't have any file then it is game's fault.

**Comment by Bisquit0** [comment]
>  The inventory and map interface will disappear can be cause by -dev but other things happens because of apex, mainly that cursor. For crashes I don't know, it would be your PC, check if it has any file in crashpad (C:\Program Files (x86)\Steam\steamapps\common\Apex Legends\Crashpad\db) if it doesn't have any file then it is game's fault. 

It didn't happen again, all is well.  Thank you.

**Comment by Natram1zh** [comment]
Noice, I am closing this issue since original poster is not chatting.
