### ISSUE TITLE
setting.stream_memory set to 0 is working but 9999999 is not

### ISSUE THREAD

**Issue by takaqiao** [Natram1zh/Apex-Legends-Config-And-Tweaks#8]
The texture is down scaled(blurred)when it set to 0 and the 999999setting is not working
my current setting below
`"VideoConfig"
{
	"setting.cl_gib_allow"		"0"
	"setting.cl_particle_fallback_base"		"0"
	"setting.cl_particle_fallback_multiplier"		"0"
	"setting.cl_ragdoll_maxcount"		"0"
	"setting.cl_ragdoll_self_collision"		"0"
	"setting.mat_forceaniso"		"1"
	"setting.mat_mip_linear"		"0"
	"setting.stream_memory"		"0"
	"setting.mat_picmip"		"0"
	"setting.particle_cpu_level"		"0"
	"setting.r_createmodeldecals"		"0"
	"setting.r_decals"		"0"
	"setting.r_lod_switch_scale"		"0.350000"
	"setting.shadow_enable"		"0"
	"setting.shadow_depth_dimen_min"		"0"
	"setting.shadow_depth_upres_factor_max"		"0"
	"setting.shadow_maxdynamic"		"0"
	"setting.ssao_enabled"		"0"
	"setting.ssao_downsample"		"3"
	"setting.dvs_enable"		"0"
	"setting.dvs_gpuframetime_min"		"5000"
	"setting.dvs_gpuframetime_max"		"6500"
	"setting.nowindowborder"		"0"
	"setting.fullscreen"		"1"
	"setting.defaultres"		"2560"
	"setting.defaultresheight"		"1440"
	"setting.volumetric_lighting"		"0"
	"setting.volumetric_fog"		"0"
	"setting.mat_vsync_mode"		"0"
	"setting.mat_backbuffer_count"		"1"
	"setting.mat_antialias_mode"		"0"
	"setting.csm_enabled"		"1"
	"setting.csm_coverage"		"1"
	"setting.csm_cascade_res"		"512"
	"setting.fadeDistScale"		"1.000000"
	"setting.dvs_supersample_enable"		"0"
	"setting.new_shadow_settings"		"1"
	"setting.gamma"		"1.000000"
	"setting.configversion"		"7"
}
`

**Comment by takaqiao** [comment]
Do u have any idea why 999999 is not working anymore? and is there any improvement I can adjust my current one.(I compared&googled many settings&suggestions,but yours r the best config ever)

**Comment by Natram1zh** [comment]
I have no idea, personally I use 3000000 [DX11] or 600000 [DX12]
stream_memory highest value is 3000000

stream_memory "600000" // Quality of textures 
Use this value according to your GPU VRAM
[In game values]
 8GB = 3000000
 6GB = 2000000
 4GB = 1000000
 3GB = 600000
 2GB = 160000
 None = 0
 
 For improvements 
 "setting.cl_particle_fallback_base" "3" 
 "setting.cl_particle_fallback_multiplier" "2"
 "setting.r_lod_switch_scale" "0.5" or "0.4"
 "setting.csm_enabled" "0"
 "setting.csm_cascade_res" "0"
 
 Note : Don't change settings in game [video tab] because it will bring back shadows

**Comment by takaqiao** [comment]
Thanks:)
